/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package io.fcash.costumer;

import io.fcash.costumer.register.*;

/**
 *
 * @author Champ
 */
public class Registration extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registration.class.getName());
    
    //form 1
    public static String firstname;
    public static String middlename;
    public static String lastname;
    public static String suffix;
    public static String mothersMaidenfirstname;
    public static String mothersMaidenmiddlename;
    public static String mothersMaidenlastname;
    public static String mothersMaidensuffix;
    public static String mobileNumber;
    public static String residentialNumber = "";
    public static String dateOfbirth;
    public static String email;
    public static String emailhost;
    
    //form 2
    public static String gender;
    public static String civilStatus;
    public static String nationality;
    public static String placeOfBirth;
    public static String residential_Address_HouseNumber;
    public static String residential_Address_Street;
    public static String residential_Address_Barangay;
    public static String residential_Address_Province;
    public static String residential_Address_zipcode;
    public static String permanent_Address_HouseNumber;
    public static String permanent_Address_Street;
    public static String permanent_Address_Barangay;
    public static String permanent_Address_Province;
    public static String permanent_Address_zipcode;
    
    public static String username;
    public static String password;
    
    public static String accountType = "";
    public static boolean updateAccount;
    public static int userID;
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * Creates new form registration
     */
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("jfmregister"); // NOI18N
        setPreferredSize(null);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                loadcomplete(evt);
            }
        });

        setSize(new java.awt.Dimension(650, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loadcomplete(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_loadcomplete
        // TODO add your handling code here:
        jplPersonInfo_form1 pInfo = new jplPersonInfo_form1();
        getContentPane().add(pInfo);
        revalidate();
        repaint();
    }//GEN-LAST:event_loadcomplete
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registration().setVisible(true));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
