/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package io.fcash.costumer.account;

import java.sql.*;
import io.fcash.Database;
import io.fcash.costumer.Login;
import io.fcash.costumer.Registration;

/**
 *
 * @author Champ
 */
public class Profile extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Profile.class.getName());
    
    public static int userid;
    
    
    /**
     * Creates new form profile
     */
    public Profile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFullname = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        btnEditAccount = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("jfProfile"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblFullname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFullname.setText("Name");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Available Balance:");

        lblBalance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBalance.setText("₱ ");

        btnEditAccount.setText("Edit Account");
        btnEditAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditAccountMouseClicked(evt);
            }
        });

        btnLogout.setText("Log Out");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });

        jButton4.setText("Transaction");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblFullname))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditAccount)
                                .addGap(18, 18, 18)
                                .addComponent(btnLogout))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(lblBalance)))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblFullname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblBalance))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(btnEditAccount)
                    .addComponent(jButton4))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loadData();
    }//GEN-LAST:event_formWindowOpened

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        TransactionLog TLog = new TransactionLog();
        TLog.setVisible(true);
        TLog.userid = userid;
    }//GEN-LAST:event_jButton4MouseClicked

    private void btnEditAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditAccountMouseClicked
        //registration but using UI form only, then method for updating Info.
        Registration register = new Registration();
        register.setVisible(true);
        register.accountType = "costumer";
        register.userID = userid;
        register.updateAccount = true;
        
    }//GEN-LAST:event_btnEditAccountMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        loadData();
    }//GEN-LAST:event_formWindowActivated

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Profile().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditAccount;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblFullname;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        
        String select_query = "SELECT \n" +
            "acc.id,\n" +
            "profile.firstname,\n" +
            "profile.middlename,\n" +
            "profile.lastname,\n" +
            "profile.suffix,\n" +
            "accSave.balance\n" +
            "FROM `tblaccount` AS acc \n" +
            "INNER JOIN `tblprofile` AS profile\n" +
            "ON acc.id = profile.profileID \n" +
            "INNER JOIN `tblsavingsaccount` AS accSave\n" +
            "ON acc.id = accSave.id \n"+
            "WHERE acc.id = ?;";
        Connection con = null;
        ResultSet rs;
        try {
            con = DriverManager.getConnection(Database.dbURL, Database.dbUsername, Database.dbPassword);
            PreparedStatement pstmt = con.prepareStatement(select_query);
            pstmt.setInt(1, userid);
            
            rs = pstmt.executeQuery();
        
            if (rs.next()) { 
                String firstname = rs.getString("firstname").toUpperCase();
                String middlename = rs.getString("middlename").toUpperCase();
                String lastname = rs.getString("lastname").toUpperCase();
                String suffix = rs.getString("suffix").toUpperCase();
                double balance = rs.getDouble("balance");
                
                lblFullname.setText(firstname+" "+middlename+" "+lastname+" "+suffix);
                lblBalance.setText("₱ "+balance);
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        } finally {
            if (con != null) {
                try {
                    con.close();
                } catch (SQLException closeEx) {
                    System.out.println(closeEx);
                }
            }
        }
        
    }
}
