/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package io.fcash.dashboard.admin;

import static io.fcash.costumer.account.Profile.userid;
import io.fcash.costumer.Registration;
import io.fcash.Database;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Champ
 */
public class Account extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Account.class.getName());

    public static int userid = 0;
    
    /**
     * Creates new form costumerAccount
     */
    public Account() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAccount = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnviewprofile = new javax.swing.JButton();
        btnActivateAccount = new javax.swing.JButton();
        btnAccChangeStatus = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnNewAcc = new javax.swing.JButton();
        btnViewTransaction = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("costumerAccount"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Full Name", "Account Status", "Document Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAccountMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAccount);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Account List");

        btnviewprofile.setText("View Profile");
        btnviewprofile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnviewprofileMouseClicked(evt);
            }
        });

        btnActivateAccount.setText("Activate Account");
        btnActivateAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActivateAccountMouseClicked(evt);
            }
        });

        btnAccChangeStatus.setText("Change Account Status");
        btnAccChangeStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAccChangeStatusMouseClicked(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });

        btnNewAcc.setText("New Account");
        btnNewAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewAccMouseClicked(evt);
            }
        });

        btnViewTransaction.setText("View Transaction");
        btnViewTransaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewTransactionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(145, 145, 145)
                        .addComponent(txtSearch)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnActivateAccount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnviewprofile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAccChangeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewAcc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewTransaction, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnviewprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActivateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAccChangeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNewAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(720, 544));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        refreshTableData();
    }//GEN-LAST:event_formWindowOpened

    private void tblAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAccountMouseClicked
        
        
    }//GEN-LAST:event_tblAccountMouseClicked

    private void btnAccChangeStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccChangeStatusMouseClicked
        String[] choices = { "Active", "Dormant", "Frozen", "Closed"};
        
        String selection = (String) JOptionPane.showInputDialog(
            null,                          
            "Account status change:",    
            "Status Type:",            
            JOptionPane.QUESTION_MESSAGE,  
            null,                          
            choices,                    
            choices[0]                     
        );

        int row = tblAccount.getSelectedRow();
        int modelRow = tblAccount.convertRowIndexToModel(row);
        int id = (int)tblAccount.getModel().getValueAt(modelRow, 0);
                
        if (selection.equalsIgnoreCase("Active")) {
            changeAccountStatus(id, "Active");
        }else if (selection.equalsIgnoreCase("Dormant")) {
            changeAccountStatus(id, "Dormant");
        }else if (selection.equalsIgnoreCase("Frozen")) {
            changeAccountStatus(id, "Frozen");
        }else if (selection.equalsIgnoreCase("Closed")) {
            changeAccountStatus(id, "Closed");
        }
    }//GEN-LAST:event_btnAccChangeStatusMouseClicked

    private void btnNewAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewAccMouseClicked
        
        String[] choices = {"Administrator","Account Holder","Costumer"};
        
        String selection = (String) JOptionPane.showInputDialog(
            null,                          // Parent component
            "Create an account for:",    // Message
            "Account Type",             // Title
            JOptionPane.QUESTION_MESSAGE,  // Message type
            null,                          // Icon (null for default)
            choices,                       // Array of options
            choices[0]                     // Initial selection
        );

        if (selection.equalsIgnoreCase("costumer")) {
            loadCreateAccount(selection);
        }else if (selection.equalsIgnoreCase("account holder")) {
            loadCreateAccount(selection);
        }else if (selection.equalsIgnoreCase("administrator")) {
            loadCreateAccount(selection);
        }
    }//GEN-LAST:event_btnNewAccMouseClicked

    private void btnViewTransactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewTransactionMouseClicked
        Transaction transact = new Transaction();
        transact.setVisible(true);
    }//GEN-LAST:event_btnViewTransactionMouseClicked

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        DefaultTableModel tableModel = (DefaultTableModel) tblAccount.getModel();
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(tableModel);
        tblAccount.setRowSorter(sorter);
        if (txtSearch.getText().trim().equals("")) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + txtSearch.getText(), 0)); 
        }
    }//GEN-LAST:event_btnSearchMouseClicked

    private void btnviewprofileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnviewprofileMouseClicked
        //get hidden ID
        int row = tblAccount.getSelectedRow();
        int modelRow = tblAccount.convertRowIndexToModel(row);
        int id = (int)tblAccount.getModel().getValueAt(modelRow, 0);
        Profile prof = new Profile();
        prof.setVisible(true);
        prof.userid = id;
        System.out.print("asdsa");
    }//GEN-LAST:event_btnviewprofileMouseClicked

    private void btnActivateAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActivateAccountMouseClicked
        int result = JOptionPane.showConfirmDialog(
            null,
            "Do you want to save changes?", 
            "Confirm Action",
            JOptionPane.YES_NO_OPTION
        );
        String query = "UPDATE `tblsavingsaccount` SET accountStatus = ?, openingDate = NOW() WHERE id = ?";
        
        // Process the result
        if (result == JOptionPane.YES_OPTION) {
            
            try {
                Connection con = DriverManager.getConnection(Database.dbURL, Database.dbUsername, Database.dbPassword);
                PreparedStatement stmt = con.prepareStatement(query);
                
                //get hidden ID
                int row = tblAccount.getSelectedRow();
                int modelRow = tblAccount.convertRowIndexToModel(row);
                int id = (int)tblAccount.getModel().getValueAt(modelRow, 0);
                
                stmt.setString(1, "Active"); 
                stmt.setInt(2, id);
                
                stmt.executeUpdate();
                
                
            } catch (SQLException ex) {
                System.getLogger(Account.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
        refreshTableData();
    }//GEN-LAST:event_btnActivateAccountMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Account().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccChangeStatus;
    private javax.swing.JButton btnActivateAccount;
    private javax.swing.JButton btnNewAcc;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewTransaction;
    private javax.swing.JButton btnviewprofile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAccount;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void refreshTableData() {
        String query = "SELECT \n" +
            "acc.id AS id,\n" +
            "profile.firstname AS firstname, \n" +
            "profile.middlename AS middlename, \n" +
            "profile.lastname AS lastname, \n" +
            "profile.suffix AS suffix, \n" +
            "accSave.accountStatus AS status\n" +
            "FROM `tblaccount` AS acc\n" +
            "INNER JOIN `tblprofile` AS profile \n" +
            "ON acc.id = profile.profileID \n" +
            "INNER JOIN `tblsavingsaccount` AS accSave\n" +
            "ON acc.id = accSave.id;";
            
        DefaultTableModel model = new DefaultTableModel(new String[]{"ID", "Full Name", "Account Status"}, 0);
        Connection con = null;
        try {
            con = DriverManager.getConnection(Database.dbURL, Database.dbUsername, Database.dbPassword);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            
            while (rs.next()) {
                int id = rs.getInt("id");
                String fullname = rs.getString("lastname")+" "+rs.getString("suffix")+", "+rs.getString("firstname")+" "+rs.getString("middlename");
                String status = rs.getString("status");

                // Add row to the model
                model.addRow(new Object[]{id, fullname, status, ""});
                
            }
            
            tblAccount.setModel(model);
            tblAccount.removeColumn(tblAccount.getColumnModel().getColumn(0));
        } catch (SQLException ex) {
            System.out.println(ex);
        } finally {
            if (con != null) {
                try {
                    con.close();
                } catch (SQLException closeEx) {
                    System.out.println(closeEx);
                }
            }
        }
        
    
    }

    private void loadCreateAccount(String accType) {
        Registration register = new Registration();
        register.setVisible(true);
        register.accountType = accType;
    }

    private void changeAccountStatus(int id, String status) {
        String update_query = "UPDATE `tblsavingsaccount` SET `accountStatus`= ? WHERE `id`= ?;";
        Connection con = null;
            try {
                    con = DriverManager.getConnection(Database.dbURL, Database.dbUsername, Database.dbPassword);
                    PreparedStatement pstmt = con.prepareStatement(update_query);
                    pstmt.setString(1, status);
                    pstmt.setInt(2, id);
                    pstmt.executeUpdate();
                    JOptionPane.showMessageDialog(null, 
                "Account Status Updated.", 
                "Account.", 
                JOptionPane.INFORMATION_MESSAGE);
                    refreshTableData();
                } catch (SQLException ex) {
                    if (con != null) {
                        try {
                            con.rollback();
                        } catch (SQLException rollbackEx) {
                            System.out.println(rollbackEx);
                        }
                    }
                } finally {
                    if (con != null) {
                        try {
                            con.close();
                        } catch (SQLException closeEx) {
                            System.out.println(closeEx);
                        }
                    }
                }
    
    
    }
}
