/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package io.fcash.dashboard.admin;

import io.fcash.Database;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Champ
 */
public class Profile extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Profile.class.getName());
    public static int userid = 0;    /**
     * Creates new form Profile
     */
    public Profile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbldateofbirth = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblfullname = new javax.swing.JLabel();
        lblgender = new javax.swing.JLabel();
        lblcivilstatus = new javax.swing.JLabel();
        lblnationality = new javax.swing.JLabel();
        lblplaceofbirth = new javax.swing.JLabel();
        lblfullresidentialaddr = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblfullpermanentaddr = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblmothermaidenname = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblmobilenumb = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblresidentialnumb = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbldateofbirth.setText("Date of Birth sample");

        lblemail.setText("E-mail Address sample");

        jLabel8.setText("Date of Birth:");

        jLabel10.setText("E-mail Address:");

        jLabel4.setText("Gender:");

        jLabel5.setText("Civil Status:");

        jLabel6.setText("Nationality");

        jLabel11.setText("Place of Birth:");

        jLabel12.setText("Residential Address:");

        jLabel14.setText("Permanent Address:");

        lblfullname.setText("Fullname sample");

        lblgender.setText("Gender sample");

        lblcivilstatus.setText("Civil Status sample");

        lblnationality.setText("Nationality sample");

        lblplaceofbirth.setText("Place of Birth sample");

        lblfullresidentialaddr.setText("Residential Address sample");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Account Profile:");

        lblfullpermanentaddr.setText("Permanent Address sample");

        lblmothermaidenname.setText("Mother's Maiden name sample");

        jLabel2.setText("Mother's Maiden Name:");

        lblmobilenumb.setText("Mobile no. sample");

        jLabel3.setText("Full Name:");

        lblresidentialnumb.setText("Residential no. sample");

        jLabel7.setText("Mobile no.:");

        jLabel9.setText("Residential no.:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblfullname)
                            .addComponent(lblmobilenumb)
                            .addComponent(lblresidentialnumb)
                            .addComponent(lblgender)
                            .addComponent(lblcivilstatus)
                            .addComponent(lblnationality)
                            .addComponent(lblplaceofbirth)
                            .addComponent(lblfullresidentialaddr)
                            .addComponent(lblfullpermanentaddr)
                            .addComponent(lbldateofbirth)
                            .addComponent(lblemail)
                            .addComponent(lblmothermaidenname)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblfullname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblmothermaidenname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblmobilenumb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblresidentialnumb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbldateofbirth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblemail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblgender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcivilstatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblnationality)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblplaceofbirth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblfullresidentialaddr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblfullpermanentaddr)))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loadData();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Profile().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblcivilstatus;
    private javax.swing.JLabel lbldateofbirth;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblfullname;
    private javax.swing.JLabel lblfullpermanentaddr;
    private javax.swing.JLabel lblfullresidentialaddr;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblmobilenumb;
    private javax.swing.JLabel lblmothermaidenname;
    private javax.swing.JLabel lblnationality;
    private javax.swing.JLabel lblplaceofbirth;
    private javax.swing.JLabel lblresidentialnumb;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
    
        String select_query = "SELECT \n" +
            "acc.id,\n" +
            "profile.firstname,\n" +
            "profile.middlename,\n" +
            "profile.lastname,\n" +
            "profile.suffix,\n" +
            "profile.mothersmaidenfirstname AS mothersmaidenfirstname, \n" +
            "profile.mothersmaidenmiddlename AS mothersmaidenmiddlename, \n" +
            "profile.mothersmaidenlastname AS mothersmaidenlastname, \n" +
            "profile.mothersmaidensuffix AS mothersmaidensuffix, \n" +
            "profile.mobilenumber AS mobilenumber, \n" +
            "profile.residentialnumber AS residentialnumber, \n" +
            "profile.dateofbirth AS dateofbirth, \n" +
            "profile.email AS email, \n" +
            "profile.nationality AS nationality, \n" +
            "profile.placeofbirth AS placeofbirth, \n" +
            "profile.gender AS gender, \n" +
            "profile.civilstatus AS civilstatus, \n" +
            "profile.res_Address_HouseNumber AS res_Address_HouseNumber, \n" +
            "profile.res_Address_Street AS res_Address_Street, \n" +
            "profile.res_Address_Barangay AS res_Address_Barangay, \n" +
            "profile.res_Address_Province AS res_Address_Province, \n" +
            "profile.res_Address_zipcode AS res_Address_zipcode, \n" +
            "profile.per_Address_HouseNumber AS per_Address_HouseNumber, \n" +
            "profile.per_Address_Street AS per_Address_Street, \n" +
            "profile.per_Address_Barangay AS per_Address_Barangay, \n" +
            "profile.per_Address_Province AS per_Address_Province, \n" +
            "profile.per_Address_zipcode AS per_Address_zipcode \n" +
            "FROM `tblaccount` AS acc \n" +
            "INNER JOIN `tblprofile` AS profile\n" +
            "ON acc.id = profile.profileID\n" +
            "INNER JOIN `tblsavingsaccount` AS accSave\n" +
            "ON acc.id = accSave.id \n"+
            "WHERE acc.id = ?;";
        Connection con = null;
        ResultSet rs;
        
        try {
            con = DriverManager.getConnection(Database.dbURL, Database.dbUsername, Database.dbPassword);
            PreparedStatement pstmt = con.prepareStatement(select_query);
            pstmt.setInt(1, userid);
            
            rs = pstmt.executeQuery();
        
            if (rs.next()) { 
                String firstname = rs.getString("firstname").toUpperCase();
                String middlename = rs.getString("middlename").toUpperCase();
                String lastname = rs.getString("lastname").toUpperCase();
                String suffix = rs.getString("suffix").toUpperCase();
                String mothersmaidenfirstname = rs.getString("mothersmaidenfirstname").toUpperCase();
                String mothersmaidenmiddlename = rs.getString("mothersmaidenmiddlename").toUpperCase();
                String mothersmaidenlastname = rs.getString("mothersmaidenlastname").toUpperCase();
                String mothersmaidensuffix = rs.getString("mothersmaidensuffix").toUpperCase();
                
                lblmobilenumb.setText(rs.getString("mobilenumber"));
                lblresidentialnumb.setText(rs.getString("residentialnumber"));
                lbldateofbirth.setText(rs.getString("dateofbirth"));
                lblemail.setText(rs.getString("email"));
                lblgender.setText(rs.getString("gender"));
                lblcivilstatus.setText(rs.getString("civilstatus"));
                lblnationality.setText(rs.getString("nationality"));
                lblplaceofbirth.setText(rs.getString("placeofbirth"));
                String res_Address_HouseNumber = rs.getString("res_Address_HouseNumber").toUpperCase();
                String res_Address_Street = rs.getString("res_Address_Street").toUpperCase();
                String res_Address_Barangay = rs.getString("res_Address_Barangay").toUpperCase();
                String res_Address_Province = rs.getString("res_Address_Province").toUpperCase();
                String res_Address_zipcode = rs.getString("res_Address_zipcode").toUpperCase();
                String per_Address_HouseNumber = rs.getString("per_Address_HouseNumber").toUpperCase();
                String per_Address_Street = rs.getString("per_Address_Street").toUpperCase();
                String per_Address_Barangay = rs.getString("per_Address_Barangay").toUpperCase();
                String per_Address_Province = rs.getString("per_Address_Province").toUpperCase();
                String per_Address_zipcode = rs.getString("per_Address_zipcode").toUpperCase();
                
                lblfullresidentialaddr.setText(res_Address_HouseNumber + " " + res_Address_Street + " " + res_Address_Barangay + " " + res_Address_Province + " " + res_Address_zipcode);
                lblfullpermanentaddr.setText(per_Address_HouseNumber + " " + per_Address_Street + " " + per_Address_Barangay + " " + per_Address_Province + " " + per_Address_zipcode);
                
                lblfullname.setText(firstname+" "+middlename+" "+lastname+" "+suffix);
                lblmothermaidenname.setText(mothersmaidenfirstname+" "+mothersmaidenmiddlename+" "+mothersmaidenlastname+" "+mothersmaidensuffix);
                
                
                
                
            }else{
                System.out.println("erre");
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        } finally {
            if (con != null) {
                try {
                    con.close();
                } catch (SQLException closeEx) {
                    System.out.println(closeEx);
                }
            }
        }
        
    
    }
}
