/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package io.fcash.costumer.register;

import io.fcash.costumer.Login;
import io.fcash.costumer.Registration;
import static io.fcash.costumer.Registration.accountType;
import io.fcash.dashboard.admin.Account;
import java.sql.*;
import io.fcash.Database;
import static io.fcash.costumer.Registration.userID;
import java.awt.Window;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import static javax.swing.SwingUtilities.getWindowAncestor;

/**
 *
 * @author Champ
 */
public class jplPersonInfo_Review extends javax.swing.JPanel {
    
    private static String firstname = Registration.firstname;
    private static String middlename  = Registration.middlename;
    private static String lastname  = Registration.lastname;
    private static String suffix = Registration.suffix;
    private static String mothersMaidenfirstname = Registration.mothersMaidenfirstname;
    private static String mothersMaidenmiddlename = Registration.mothersMaidenmiddlename;
    private static String mothersMaidenlastname = Registration.mothersMaidenlastname;
    private static String mothersMaidensuffix = Registration.mothersMaidensuffix;
    private static String mobileNumber = Registration.mobileNumber;
    private static String residentialNumber = Registration.residentialNumber;
    private static String dateOfbirth = Registration.dateOfbirth;
    private static String email = Registration.email;
    private static String emailhost = Registration.emailhost;
    
    //form 2
    private static String gender = Registration.gender;
    private static String civilStatus = Registration.civilStatus;
    private static String nationality = Registration.nationality;
    private static String placeOfBirth = Registration.placeOfBirth;
    private static String residential_Address_HouseNumber = Registration.residential_Address_HouseNumber;
    private static String residential_Address_Street = Registration.residential_Address_Street;
    private static String residential_Address_Barangay = Registration.residential_Address_Barangay;
    private static String residential_Address_Province = Registration.residential_Address_Province;
    private static String residential_Address_zipcode = Registration.residential_Address_zipcode;
    private static String permanent_Address_HouseNumber = Registration.permanent_Address_HouseNumber;
    private static String permanent_Address_Street = Registration.permanent_Address_Street;
    private static String permanent_Address_Barangay = Registration.permanent_Address_Barangay;
    private static String permanent_Address_Province = Registration.permanent_Address_Province;
    private static String permanent_Address_zipcode = Registration.permanent_Address_zipcode;
    
    private static String username;
    private static String password;
    
    /**
     * Creates new form jplPersonInfo_Review
     */
    public jplPersonInfo_Review() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblfullname = new javax.swing.JLabel();
        lblgender = new javax.swing.JLabel();
        lblcivilstatus = new javax.swing.JLabel();
        lblnationality = new javax.swing.JLabel();
        lblplaceofbirth = new javax.swing.JLabel();
        lblfullresidentialaddr = new javax.swing.JLabel();
        lblfullpermanentaddr = new javax.swing.JLabel();
        lblmothermaidenname = new javax.swing.JLabel();
        lblmobilenumb = new javax.swing.JLabel();
        lblresidentialnumb = new javax.swing.JLabel();
        lbldateofbirth = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        lblnewpassword = new javax.swing.JLabel();
        cbChangePW = new javax.swing.JCheckBox();
        txtPassword = new javax.swing.JPasswordField();
        txtNewPassword = new javax.swing.JPasswordField();
        lblrepassword = new javax.swing.JLabel();
        txtRePassword = new javax.swing.JPasswordField();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Personal Information:");

        jLabel2.setText("Mother's Maiden Name:");

        jLabel3.setText("Full Name:");

        jLabel7.setText("Mobile no.:");

        jLabel9.setText("Residential no.:");

        jLabel8.setText("Date of Birth:");

        jLabel10.setText("E-mail Address:");

        jLabel4.setText("Gender:");

        jLabel5.setText("Civil Status:");

        jLabel6.setText("Nationality");

        jLabel11.setText("Place of Birth:");

        jLabel12.setText("Residential Address:");

        jLabel14.setText("Permanent Address:");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(this::btnSubmitActionPerformed);

        jButton2.setText("<- Back");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        lblfullname.setText("Fullname sample");

        lblgender.setText("Gender sample");

        lblcivilstatus.setText("Civil Status sample");

        lblnationality.setText("Nationality sample");

        lblplaceofbirth.setText("Place of Birth sample");

        lblfullresidentialaddr.setText("Residential Address sample");

        lblfullpermanentaddr.setText("Permanent Address sample");

        lblmothermaidenname.setText("Mother's Maiden name sample");

        lblmobilenumb.setText("Mobile no. sample");

        lblresidentialnumb.setText("Residential no. sample");

        lbldateofbirth.setText("Date of Birth sample");

        lblemail.setText("E-mail Address sample");

        jLabel15.setText("Username:");

        lblpassword.setText("Password:");

        lblnewpassword.setText("New Password");

        cbChangePW.setText("Change Password");
        cbChangePW.addChangeListener(this::cbChangePWStateChanged);

        lblrepassword.setText("Re-type Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel14)
                                .addComponent(jLabel12)
                                .addComponent(jLabel11)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel7)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(71, 71, 71)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblfullname)
                                .addComponent(lblmobilenumb)
                                .addComponent(lblresidentialnumb)
                                .addComponent(lblcivilstatus)
                                .addComponent(lblnationality)
                                .addComponent(lblplaceofbirth)
                                .addComponent(lblfullresidentialaddr)
                                .addComponent(lblfullpermanentaddr)
                                .addComponent(lbldateofbirth)
                                .addComponent(lblmothermaidenname)
                                .addComponent(lblgender)
                                .addComponent(lblemail))
                            .addGap(139, 139, 139))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbChangePW)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(lblpassword))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtUsername)
                                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblnewpassword)
                                            .addComponent(lblrepassword))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtRePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblfullname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblmothermaidenname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblmobilenumb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblresidentialnumb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbldateofbirth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblemail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblgender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcivilstatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblnationality)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblplaceofbirth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblfullresidentialaddr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblfullpermanentaddr))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblpassword)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbChangePW))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblnewpassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblrepassword)
                            .addComponent(txtRePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(220, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        if(Registration.updateAccount==true){
            cbChangePW.setVisible(true);
            lblpassword.setText("Password:");
            txtPassword.setVisible(true);
            lblnewpassword.setVisible(false);
            txtNewPassword.setVisible(false);
            lblrepassword.setVisible(false);
            txtRePassword.setVisible(false);
            txtUsername.setEnabled(false);
            
        }
        else{
            cbChangePW.setVisible(false);
            lblnewpassword.setVisible(true);
            txtNewPassword.setVisible(true);
            lblnewpassword.setVisible(false);
            txtNewPassword.setVisible(false);
            lblrepassword.setVisible(true);
            txtRePassword.setVisible(true);
            
        }
        
        
        lblfullname.setText(firstname+" "+middlename+" "+lastname+" "+suffix);
        lblmothermaidenname.setText(mothersMaidenfirstname+" "+mothersMaidenmiddlename+" "+mothersMaidenlastname+" "+mothersMaidensuffix);
        lblmobilenumb.setText(mobileNumber);
        lblresidentialnumb.setText(residentialNumber);
        lbldateofbirth.setText(dateOfbirth);
        lblemail.setText(email+"@"+emailhost);
        
        lblgender.setText(gender);
        lblcivilstatus.setText(civilStatus);
        lblnationality.setText(nationality);
        lblplaceofbirth.setText(placeOfBirth);
        String full_Residential_Address = residential_Address_HouseNumber+" "+residential_Address_Street+"Street, Brgy. "+residential_Address_Barangay+" "+residential_Address_Province+", "+residential_Address_zipcode;
        lblfullresidentialaddr.setText(full_Residential_Address);
        String full_Permanent_Address = permanent_Address_HouseNumber+" "+permanent_Address_Street+"Street, Brgy. "+permanent_Address_Barangay+" "+permanent_Address_Province+", "+permanent_Address_zipcode;
        lblfullpermanentaddr.setText(full_Permanent_Address);
        
        if(Registration.updateAccount == true){
            btnSubmit.setText("Update");
        }
        loadFormData(userID);
    }//GEN-LAST:event_formAncestorAdded

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if(Registration.updateAccount==true){
            updateAccount(Registration.userID);
        }else{
            newAccount();
        }
        
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

        JFrame jfregister = (JFrame) SwingUtilities.getAncestorOfClass(JFrame.class, this);
        jplPersonInfo_form2 pInfoF2 = new jplPersonInfo_form2();
        jfregister.remove(this); 
        jfregister.getContentPane().add(pInfoF2);
        jfregister.revalidate();
        jfregister.repaint();
    }//GEN-LAST:event_jButton2MouseClicked

    private void cbChangePWStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbChangePWStateChanged
        if(cbChangePW.isSelected()){
            lblpassword.setText("Current Password:");
            lblnewpassword.setVisible(true);
            txtNewPassword.setVisible(true);
            lblrepassword.setVisible(true);
            txtRePassword.setVisible(true);
        }else{
            lblpassword.setText("Password:");
            lblnewpassword.setVisible(false);
            txtNewPassword.setVisible(false);
            lblrepassword.setVisible(false);
            txtRePassword.setVisible(false);
        }
        
        
    }//GEN-LAST:event_cbChangePWStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox cbChangePW;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblcivilstatus;
    private javax.swing.JLabel lbldateofbirth;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblfullname;
    private javax.swing.JLabel lblfullpermanentaddr;
    private javax.swing.JLabel lblfullresidentialaddr;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblmobilenumb;
    private javax.swing.JLabel lblmothermaidenname;
    private javax.swing.JLabel lblnationality;
    private javax.swing.JLabel lblnewpassword;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblplaceofbirth;
    private javax.swing.JLabel lblrepassword;
    private javax.swing.JLabel lblresidentialnumb;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtRePassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void newAccount() {
        username = txtUsername.getText();
        password = txtPassword.getText(); // FIX: Changed from txtRePassword to txtPassword
        String rePassword = txtRePassword.getText();

        boolean noDupUsername = false;
        boolean rePWMatched = false;
        int id = 0;

        String checkUser = "SELECT COUNT(*) FROM `tblaccount` WHERE username = ?";
        String sqlAccount = "INSERT INTO `tblaccount` (`username`, `password`, `type`) VALUES (?, ?, ?);";
        String sqlprofile = "INSERT INTO `tblprofile` (`profileID`, `firstname`, `middlename`, `lastname`, `suffix`, `mothersmaidenfirstname`, `mothersmaidenmiddlename`, `mothersmaidenlastname`, `mothersmaidensuffix`, `mobilenumber`, `residentialnumber`, `dateofbirth`, `email`, `gender`, `civilstatus`, `nationality`, `placeofbirth`, `res_Address_HouseNumber`, `res_Address_Street`, `res_Address_Barangay`, `res_Address_Province`, `res_Address_zipcode`, `per_Address_HouseNumber`, `per_Address_Street`, `per_Address_Barangay`, `per_Address_Province`, `per_Address_zipcode`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";
        String sqlsavings = "INSERT INTO `tblsavingsaccount` (id, accountStatus) VALUES (?, ?);";

        if (password.equals(rePassword)) {
            rePWMatched = true;
        } else {
            JOptionPane.showMessageDialog(null, 
                    "Password And Re-Password Do Not Match.", 
                    "Password Error", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        try (Connection con = DriverManager.getConnection(Database.dbURL, Database.dbUsername, Database.dbPassword)) {

            try (PreparedStatement checkStmt = con.prepareStatement(checkUser)) {
                checkStmt.setString(1, username);
                try (ResultSet rs = checkStmt.executeQuery()) {
                    if (rs.next() && rs.getInt(1) > 0) {
                        JOptionPane.showMessageDialog(null, 
                            "The Username is already taken.", 
                            "Username Error", 
                            JOptionPane.WARNING_MESSAGE);
                        return; // STOP execution here
                    } else {
                        noDupUsername = true;
                    }
                }
            }

            if (noDupUsername && rePWMatched) {
                int result = JOptionPane.showConfirmDialog(
                    null,
                    "Do you want to save changes?", 
                    "Confirm Action",
                    JOptionPane.YES_NO_OPTION
                );

                if (result == JOptionPane.YES_OPTION) {
                    try {
                        con.setAutoCommit(false);

                        try (PreparedStatement pstmtAcc = con.prepareStatement(sqlAccount, Statement.RETURN_GENERATED_KEYS)) {
                            pstmtAcc.setString(1, username);
                            pstmtAcc.setString(2, password);
                            pstmtAcc.setString(3, accountType);
                            pstmtAcc.executeUpdate();

                            try (ResultSet rs = pstmtAcc.getGeneratedKeys()) {
                                if (rs.next()) {
                                    id = rs.getInt(1);
                                }
                            }
                        }

                        try (PreparedStatement pstmtProf = con.prepareStatement(sqlprofile)) {
                            pstmtProf.setInt(1, id);
                            pstmtProf.setString(2, firstname);
                            pstmtProf.setString(3, middlename);
                            pstmtProf.setString(4, lastname);
                            pstmtProf.setString(5, suffix);
                            pstmtProf.setString(6, mothersMaidenfirstname);
                            pstmtProf.setString(7, mothersMaidenmiddlename);
                            pstmtProf.setString(8, mothersMaidenlastname);
                            pstmtProf.setString(9, mothersMaidensuffix);
                            pstmtProf.setString(10, mobileNumber);
                            pstmtProf.setString(11, residentialNumber);
                            pstmtProf.setString(12, dateOfbirth);
                            pstmtProf.setString(13, email + "@" + emailhost);
                            pstmtProf.setString(14, gender);
                            pstmtProf.setString(15, civilStatus);
                            pstmtProf.setString(16, nationality);
                            pstmtProf.setString(17, placeOfBirth);
                            pstmtProf.setString(18, residential_Address_HouseNumber);
                            pstmtProf.setString(19, residential_Address_Street);
                            pstmtProf.setString(20, residential_Address_Barangay);
                            pstmtProf.setString(21, residential_Address_Province);
                            pstmtProf.setString(22, residential_Address_zipcode);
                            pstmtProf.setString(23, permanent_Address_HouseNumber);
                            pstmtProf.setString(24, permanent_Address_Street);
                            pstmtProf.setString(25, permanent_Address_Barangay);
                            pstmtProf.setString(26, permanent_Address_Province);
                            pstmtProf.setString(27, permanent_Address_zipcode);
                            pstmtProf.executeUpdate();
                        }
                        
                        if(accountType.equalsIgnoreCase("costumer")){
                            try (PreparedStatement pstmtSav = con.prepareStatement(sqlsavings)) {
                                pstmtSav.setInt(1, id);
                                pstmtSav.setString(2, "Pending");
                                pstmtSav.executeUpdate();
                            }
                        }
                        
                        con.commit();

                        JOptionPane.showMessageDialog(this, 
                            "Registration Successful!", 
                            "Success", 
                            JOptionPane.INFORMATION_MESSAGE);

                        Window win = SwingUtilities.getWindowAncestor(this); 
                        if (accountType.equalsIgnoreCase("costumer")) {
                            Login jflogin = new Login();
                            jflogin.setVisible(true);
                        } else {
                            Account jfAcc = new Account();
                            jfAcc.setVisible(true);
                        }

                        if (win != null) {
                            win.dispose();
                        }

                    } catch (SQLException ex) {
                        con.rollback(); 
                        throw ex;
                    }
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Database Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }

    private void updateAccount(int userID1) {
        String updateSQL = "UPDATE `tblprofile` SET `firstname`=?, `middlename`=?, `lastname`=?, `suffix`=?, `mothersmaidenfirstname`=?, `mothersmaidenmiddlename`=?, `mothersmaidenlastname`=?, `mothersmaidensuffix`=?, `mobilenumber`=?, `residentialnumber`=?, `dateofbirth`=?, `email`=?, `gender`=?, `civilstatus`=?, `nationality`=?, `placeofbirth`=?, `res_Address_HouseNumber`=?, `res_Address_Street`=?, `res_Address_Barangay`=?, `res_Address_Province`=?, `res_Address_zipcode`=?, `per_Address_HouseNumber`=?, `per_Address_Street`=?, `per_Address_Barangay`=?, `per_Address_Province`=?, `per_Address_zipcode`=? WHERE profileID = ?;";
        
        int result = JOptionPane.showConfirmDialog(
        null,
        "Do you want to save changes?", 
        "Confirm Action",
        JOptionPane.YES_NO_OPTION
        );
        boolean matched_password = passwordCheck(userID1);
        boolean new_password = false;
        
        if(cbChangePW.isSelected()){
            new_password = true;
        }
        
        if(matched_password == true){
            if (result == JOptionPane.YES_OPTION) {
                Connection con = null;
                try {
                    con = DriverManager.getConnection(Database.dbURL, Database.dbUsername, Database.dbPassword);
                    PreparedStatement pstmt = con.prepareStatement(updateSQL);
                    pstmt.setString(1, firstname);
                    pstmt.setString(2, middlename);
                    pstmt.setString(3, lastname);
                    pstmt.setString(4, suffix);
                    pstmt.setString(5, mothersMaidenfirstname);
                    pstmt.setString(6, mothersMaidenmiddlename);
                    pstmt.setString(7, mothersMaidenlastname);
                    pstmt.setString(8, mothersMaidensuffix);
                    pstmt.setString(9, mobileNumber);
                    pstmt.setString(10, residentialNumber);
                    pstmt.setString(11, dateOfbirth);
                    pstmt.setString(12, email+"@"+emailhost);
                    pstmt.setString(13, gender);
                    pstmt.setString(14, civilStatus);
                    pstmt.setString(15, nationality);
                    pstmt.setString(16, placeOfBirth);
                    pstmt.setString(17, residential_Address_HouseNumber);
                    pstmt.setString(18, residential_Address_Street);
                    pstmt.setString(19, residential_Address_Barangay);
                    pstmt.setString(20, residential_Address_Province);
                    pstmt.setString(21, residential_Address_zipcode);
                    pstmt.setString(22, permanent_Address_HouseNumber);
                    pstmt.setString(23, permanent_Address_Street);
                    pstmt.setString(24, permanent_Address_Barangay);
                    pstmt.setString(25, permanent_Address_Province);
                    pstmt.setString(26, permanent_Address_zipcode);
                    pstmt.setInt(27, Registration.userID);
                    pstmt.executeUpdate();
                    if(new_password == true){
                        updatePassword(Registration.userID);
                    
                    }

                    JOptionPane.showMessageDialog(this, 
                    "Update Successful!", 
                    "Success", 
                    JOptionPane.INFORMATION_MESSAGE);
                    Window win = getWindowAncestor(this);
                    win.dispose();


                } catch (SQLException ex) {
                    if (con != null) {
                        try {
                            con.rollback();
                        } catch (SQLException rollbackEx) {
                            System.out.println(rollbackEx);
                        }
                    }
                } finally {
                    if (con != null) {
                        try {
                            con.close();
                        } catch (SQLException closeEx) {
                            System.out.println(closeEx);
                        }
                    }
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, 
        "Incorrect Password.", 
        "Password.", 
        JOptionPane.INFORMATION_MESSAGE);
        }
        
                
        
        
    }
    
    private boolean passwordCheck(int userID1) {
        boolean isPasswordMatch = false;
        String query = "SELECT password FROM `tblaccount` WHERE id = ?";
        Connection con = null;
        try {
            con = DriverManager.getConnection(Database.dbURL, Database.dbUsername, Database.dbPassword);
            PreparedStatement pstmt = con.prepareStatement(query);
            pstmt.setInt(1, userID1);
            ResultSet rs = pstmt.executeQuery();
            
            if(rs.next()){
                String dbPassword = rs.getString("password");
                if(dbPassword.equals(txtPassword.getText())){
                    isPasswordMatch = true;
                }
                
            }

        } catch (SQLException ex) {
                if (con != null) {
                    try {
                        con.rollback();
                    } catch (SQLException rollbackEx) {
                        System.out.println(rollbackEx);
                    }
                }
            } finally {
                if (con != null) {
                    try {
                        con.close();
                    } catch (SQLException closeEx) {
                        System.out.println(closeEx);
                    }
                }
            }
        return isPasswordMatch;
    }

    private void updatePassword(int userID) {
        String update_query = "UPDATE `tblaccount` SET `password`= ? WHERE `id`= ?;";
        Connection con = null;
            try {
                    con = DriverManager.getConnection(Database.dbURL, Database.dbUsername, Database.dbPassword);
                    PreparedStatement pstmt = con.prepareStatement(update_query);
                    pstmt.setString(1, txtNewPassword.getText());
                    pstmt.setInt(2, Registration.userID);
                    pstmt.executeUpdate();

                } catch (SQLException ex) {
                    if (con != null) {
                        try {
                            con.rollback();
                        } catch (SQLException rollbackEx) {
                            System.out.println(rollbackEx);
                        }
                    }
                } finally {
                    if (con != null) {
                        try {
                            con.close();
                        } catch (SQLException closeEx) {
                            System.out.println(closeEx);
                        }
                    }
                }
    
    
    }

    
    private void loadFormData(int userID) {
        String query = "SELECT \n" +
            "acc.username AS username \n" +
            "FROM `tblaccount` AS acc\n" +
            "WHERE acc.id = ?;";
            
        Connection con = null;
        try {
            
            con = DriverManager.getConnection(Database.dbURL, Database.dbUsername, Database.dbPassword);
            PreparedStatement checkStmt = con.prepareStatement(query);
            checkStmt.setInt(1, userID);
            ResultSet rs = checkStmt.executeQuery();
            
            if(rs.next()) {
                txtUsername.setText(rs.getString("username"));
            }
        
        } catch (SQLException ex) {
            System.out.println(ex);
        } finally {
            if (con != null) {
                try {
                    con.close();
                } catch (SQLException closeEx) {
                    System.out.println(closeEx);
                }
            }
        }
    
    }
}
