/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package io.fcash.costumer.register;

import io.fcash.Database;
import javax.swing.*;
import io.fcash.costumer.Registration;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
/**
 *
 * @author Champ
 */
public class jplPersonInfo_form1 extends javax.swing.JPanel {

    /**
     * Creates new form jplPersonInfo
     */
    public jplPersonInfo_form1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGoToForm2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JTextField();
        txtmiddlename = new javax.swing.JTextField();
        txtlastname = new javax.swing.JTextField();
        txtsuffix = new javax.swing.JTextField();
        cbmiddlename = new javax.swing.JCheckBox();
        txtmothersmaidenfirstname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtmothersmaidenmiidlename = new javax.swing.JTextField();
        cbmothersmaidenmiddlename = new javax.swing.JCheckBox();
        txtmothersmaidenlastname = new javax.swing.JTextField();
        txtmothersmaidensuffix = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtresidentialnumber = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtemailDomain = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jdcDataofbirth = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        txtmobilenumber = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btnGoToForm2.setText("Next ->");
        btnGoToForm2.addActionListener(this::btnGoToForm2ActionPerformed);

        jLabel2.setText("First name:");

        jLabel3.setText("Middle name:");

        jLabel4.setText("Last name:");

        jLabel5.setText("Suffix:");

        cbmiddlename.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        cbmiddlename.setText("No Middle name");
        cbmiddlename.addChangeListener(this::cbmiddlenameStateChanged);

        jLabel6.setText("(Mother's Maiden Name)");

        cbmothersmaidenmiddlename.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        cbmothersmaidenmiddlename.setText("No Middle name");
        cbmothersmaidenmiddlename.addChangeListener(this::cbmothersmaidenmiddlenameStateChanged);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Personal Information:");

        jLabel11.setText("Optional");

        jLabel10.setText("E-mail Address:");

        jLabel12.setText("@");

        jLabel8.setText("Date of Birth:");

        jLabel7.setText("Mobile no.:");

        jLabel9.setText("Residential no.:");

        jLabel13.setText("Optional");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGoToForm2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(txtmiddlename, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbmiddlename, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(txtsuffix, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)))
                                .addComponent(jLabel7)
                                .addComponent(jLabel10)
                                .addComponent(jLabel8)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtemailDomain, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel13))
                                .addComponent(txtmobilenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(138, 138, 138)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtresidentialnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel11))
                                        .addComponent(jLabel9)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cbmothersmaidenmiddlename)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtmothersmaidenfirstname)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtmothersmaidenmiidlename, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addComponent(txtmothersmaidenlastname, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtmothersmaidensuffix, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6))
                                .addComponent(jdcDataofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btnGoToForm2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmiddlename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsuffix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbmiddlename)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmothersmaidenfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmothersmaidenmiidlename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmothersmaidenlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmothersmaidensuffix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbmothersmaidenmiddlename)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtmobilenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtresidentialnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcDataofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtemailDomain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(300, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoToForm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToForm2ActionPerformed
        Registration.firstname = txtfirstname.getText();
        Registration.middlename = txtmiddlename.getText();
        Registration.lastname = txtlastname.getText();
        Registration.suffix = txtsuffix.getText();
        Registration.mothersMaidenfirstname = txtmothersmaidenfirstname.getText();
        Registration.mothersMaidenmiddlename = txtmothersmaidenmiidlename.getText();
        Registration.mothersMaidenlastname = txtmothersmaidenlastname.getText();
        Registration.mothersMaidensuffix = txtmothersmaidensuffix.getText();
        Registration.mobileNumber = txtmobilenumber.getText();
        Registration.residentialNumber = txtresidentialnumber.getText();
        
        if (jdcDataofbirth.getDate() != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("MM-dd-yyyy");
            String formattedDate = sdf.format(jdcDataofbirth.getDate());
            Registration.dateOfbirth = formattedDate;
        }
        
        Registration.email = txtemail.getText();
        Registration.emailhost = txtemailDomain.getText();
        
        JFrame jfregister = (JFrame) SwingUtilities.getAncestorOfClass(JFrame.class, this);
        jplPersonInfo_form2 pInfo = new jplPersonInfo_form2();
        jfregister.remove(this); 
        jfregister.getContentPane().add(pInfo);
        jfregister.revalidate();
        jfregister.repaint();
        System.out.println(Registration.firstname);
        
    }//GEN-LAST:event_btnGoToForm2ActionPerformed

    private void cbmiddlenameStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbmiddlenameStateChanged
        
        if(cbmiddlename.isSelected()){
            txtmiddlename.setText("");
            txtmiddlename.setEnabled(false);
        }else{
            txtmiddlename.setEnabled(true);
        }
        
    }//GEN-LAST:event_cbmiddlenameStateChanged

    private void cbmothersmaidenmiddlenameStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbmothersmaidenmiddlenameStateChanged
        if(cbmothersmaidenmiddlename.isSelected()){
            txtmothersmaidenmiidlename.setText("");
            txtmothersmaidenmiidlename.setEnabled(false);
        }else{
            txtmothersmaidenmiidlename.setEnabled(true);
        }
    }//GEN-LAST:event_cbmothersmaidenmiddlenameStateChanged

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        if(Registration.updateAccount == true){
            loadFormData(Registration.userID);
        }
    }//GEN-LAST:event_formAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoToForm2;
    private javax.swing.JCheckBox cbmiddlename;
    private javax.swing.JCheckBox cbmothersmaidenmiddlename;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser jdcDataofbirth;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtemailDomain;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtmiddlename;
    private javax.swing.JTextField txtmobilenumber;
    private javax.swing.JTextField txtmothersmaidenfirstname;
    private javax.swing.JTextField txtmothersmaidenlastname;
    private javax.swing.JTextField txtmothersmaidenmiidlename;
    private javax.swing.JTextField txtmothersmaidensuffix;
    private javax.swing.JTextField txtresidentialnumber;
    private javax.swing.JTextField txtsuffix;
    // End of variables declaration//GEN-END:variables
    
    private void loadFormData(int userID) {
        String query = "SELECT \n" +
            "acc.type AS accountType, \n" +
            "profile.firstname AS firstname, \n" +
            "profile.middlename AS middlename, \n" +
            "profile.lastname AS lastname, \n" +
            "profile.suffix AS suffix, \n" +
            "profile.mothersmaidenfirstname AS mothersmaidenfirstname, \n" +
            "profile.mothersmaidenmiddlename AS mothersmaidenmiddlename, \n" +
            "profile.mothersmaidenlastname AS mothersmaidenlastname, \n" +
            "profile.mothersmaidensuffix AS mothersmaidensuffix, \n" +
            "profile.mobilenumber AS mobilenumber, \n" +
            "profile.residentialnumber AS residentialnumber, \n" +
            "profile.dateofbirth AS dateofbirth, \n" +
            "profile.email AS email \n" +
            "FROM `tblaccount` AS acc\n" +
            "INNER JOIN `tblprofile` AS profile \n" +
            "ON acc.id = profile.profileID \n"+
            "WHERE acc.id = ?;";
            
        Connection con = null;
        try {
            
            con = DriverManager.getConnection(Database.dbURL, Database.dbUsername, Database.dbPassword);
            PreparedStatement checkStmt = con.prepareStatement(query);
            checkStmt.setInt(1, userID);
            ResultSet rs = checkStmt.executeQuery();
            
            while (rs.next()) {
                Registration.accountType = rs.getString("accountType");
                txtfirstname.setText(rs.getString("firstname"));
                txtmiddlename.setText(rs.getString("middlename"));
                txtlastname.setText(rs.getString("lastname"));
                txtsuffix.setText(rs.getString("suffix"));
                txtmothersmaidenfirstname.setText(rs.getString("mothersmaidenfirstname"));
                txtmothersmaidenmiidlename.setText(rs.getString("mothersmaidenmiddlename"));
                txtmothersmaidenlastname.setText(rs.getString("mothersmaidenlastname"));
                txtmothersmaidensuffix.setText(rs.getString("mothersmaidensuffix"));
                txtmobilenumber.setText(rs.getString("mobilenumber"));
                txtresidentialnumber.setText(rs.getString("residentialnumber"));
                txtmiddlename.setText(rs.getString("middlename"));
                txtmiddlename.setText(rs.getString("middlename"));
                String mobilenumber = rs.getString("mobilenumber");
                String residentialnumber = rs.getString("residentialnumber");
                String email = rs.getString("email");
                String[] parts = email.split("@");
                String user_email = parts[0];
                String domain = parts[1]; 
                txtemail.setText(user_email);
                txtemailDomain.setText(domain);

                try {
                    String dateStr = rs.getString("dateofbirth");
                    if (dateStr != null) {
                        jdcDataofbirth.setDate(new java.text.SimpleDateFormat("MM-dd-yyyy").parse(dateStr));
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        
        } catch (SQLException ex) {
            System.out.println(ex);
        } finally {
            if (con != null) {
                try {
                    con.close();
                } catch (SQLException closeEx) {
                    System.out.println(closeEx);
                }
            }
        }
    
    }
}
    
