/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package io.fcash.costumer.register;

import io.fcash.Database;
import io.fcash.costumer.Registration;
import static io.fcash.costumer.Registration.userID;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Champ
 */
public class jplPersonInfo_form2 extends javax.swing.JPanel {

    /**
     * Creates new form jplPersonInfo_form2
     */
    public jplPersonInfo_form2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jrbtnGenderMale = new javax.swing.JRadioButton();
        jrbtnGenderFemale = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jrbtnCVSingle = new javax.swing.JRadioButton();
        jrbtnCVDivorced = new javax.swing.JRadioButton();
        jrbtnCVMarried = new javax.swing.JRadioButton();
        txtnationality = new javax.swing.JTextField();
        txtplaceOfBrith = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtResAddr_HouseNumber = new javax.swing.JTextField();
        txtResAddr_Street = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtResAddr_Barangay = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtResAddr_Province = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtResAddr_zipcode = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPermaAddr_Barangay = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPermaAddr_Province = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtPermaAddr_zipcode = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtPermaAddr_HouseNumber = new javax.swing.JTextField();
        txtPermaAddr_Street = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cbPermaAddress = new javax.swing.JCheckBox();
        btnNext = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Additional Information:");

        jLabel2.setText("Gender:");

        jrbtnGenderMale.setText("Male");
        jrbtnGenderMale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbtnGenderMaleMouseClicked(evt);
            }
        });

        jrbtnGenderFemale.setText("Female");
        jrbtnGenderFemale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbtnGenderFemaleMouseClicked(evt);
            }
        });

        jLabel3.setText("Civil Status:");

        jLabel4.setText("Nationality");

        jLabel5.setText("Place of Birth:");

        jrbtnCVSingle.setText("Single");
        jrbtnCVSingle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbtnCVSingleMouseClicked(evt);
            }
        });

        jrbtnCVDivorced.setText("Divorced");
        jrbtnCVDivorced.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbtnCVDivorcedMouseClicked(evt);
            }
        });

        jrbtnCVMarried.setText("Married");
        jrbtnCVMarried.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbtnCVMarriedMouseClicked(evt);
            }
        });

        jLabel6.setText("Residential Address:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel7.setText("Unit/House No.");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel8.setText("Street");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel9.setText("Barangay, City");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel10.setText("Province");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel11.setText("Zip Code");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel12.setText("Barangay, City");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel13.setText("Province");

        jLabel14.setText("Permanent Address:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel15.setText("Unit/House No.");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel16.setText("Zip Code");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel17.setText("Street");

        cbPermaAddress.setText("Same as Residential Address");
        cbPermaAddress.addChangeListener(this::cbPermaAddressStateChanged);

        btnNext.setText("Next ->");
        btnNext.addActionListener(this::btnNextActionPerformed);

        jButton2.setText("<- Back");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(243, 243, 243)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jrbtnCVSingle)
                                            .addComponent(jrbtnGenderMale))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jrbtnGenderFemale)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jrbtnCVMarried)
                                                .addGap(40, 40, 40)
                                                .addComponent(jrbtnCVDivorced))))
                                    .addComponent(txtnationality, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtResAddr_HouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtResAddr_Street, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtResAddr_Barangay, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(jLabel8)
                                        .addGap(108, 108, 108)
                                        .addComponent(jLabel9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtResAddr_Province, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtResAddr_zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel10)
                                        .addGap(116, 116, 116)
                                        .addComponent(jLabel11))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(cbPermaAddress))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtplaceOfBrith, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(73, 73, 73)
                                .addComponent(jLabel17)
                                .addGap(113, 113, 113)
                                .addComponent(jLabel12))
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtPermaAddr_Province, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPermaAddr_zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(txtPermaAddr_HouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPermaAddr_Street, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPermaAddr_Barangay, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel13)
                        .addGap(117, 117, 117)
                        .addComponent(jLabel16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jrbtnGenderMale)
                    .addComponent(jrbtnGenderFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jrbtnCVSingle)
                    .addComponent(jrbtnCVMarried)
                    .addComponent(jrbtnCVDivorced))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtplaceOfBrith, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResAddr_HouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResAddr_Street, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResAddr_Barangay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResAddr_Province, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResAddr_zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cbPermaAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPermaAddr_HouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPermaAddr_Street, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPermaAddr_Barangay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel15)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPermaAddr_Province, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPermaAddr_zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16))
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if(jrbtnGenderMale.isSelected())
            Registration.gender = "Male";
        else if(jrbtnGenderFemale.isSelected())
            Registration.gender = "Female";
        
        if(jrbtnCVSingle.isSelected())
            Registration.civilStatus = "Single";
        else if(jrbtnCVMarried.isSelected())
            Registration.civilStatus = "Married";
        else if(jrbtnCVDivorced.isSelected())
            Registration.civilStatus = "Divorced";
        
        Registration.nationality = txtnationality.getText();
        Registration.placeOfBirth = txtplaceOfBrith.getText();
        
        Registration.residential_Address_HouseNumber = txtResAddr_HouseNumber.getText();
        Registration.residential_Address_Street = txtResAddr_Street.getText();
        Registration.residential_Address_Barangay = txtResAddr_Barangay.getText();
        Registration.residential_Address_Province = txtResAddr_Province.getText();
        Registration.residential_Address_zipcode = txtResAddr_zipcode.getText();
        
        if(cbPermaAddress.isSelected()){
            Registration.permanent_Address_HouseNumber = txtResAddr_HouseNumber.getText();
            Registration.permanent_Address_Street = txtResAddr_Street.getText();
            Registration.permanent_Address_Barangay = txtResAddr_Barangay.getText();
            Registration.permanent_Address_Province = txtResAddr_Province.getText();
            Registration.permanent_Address_zipcode = txtResAddr_zipcode.getText();
            txtPermaAddr_HouseNumber.setText("");
            txtPermaAddr_Street.setText("");
            txtPermaAddr_Barangay.setText("");
            txtPermaAddr_Province.setText("");
            txtPermaAddr_zipcode.setText("");
            txtPermaAddr_HouseNumber.setEnabled(false);
            txtPermaAddr_Street.setEnabled(false);
            txtPermaAddr_Barangay.setEnabled(false);
            txtPermaAddr_Province.setEnabled(false);
            txtPermaAddr_zipcode.setEnabled(false);
        }else{
            Registration.permanent_Address_HouseNumber = txtPermaAddr_HouseNumber.getText();
            Registration.permanent_Address_Street = txtPermaAddr_Street.getText();
            Registration.permanent_Address_Barangay = txtPermaAddr_Barangay.getText();
            Registration.permanent_Address_Province = txtPermaAddr_Province.getText();
            Registration.permanent_Address_zipcode = txtPermaAddr_zipcode.getText();
        
        }
        
        JFrame jfregister = (JFrame) SwingUtilities.getAncestorOfClass(JFrame.class, this);
        jplPersonInfo_Review pInfo = new jplPersonInfo_Review();
        jfregister.remove(this); 
        jfregister.getContentPane().add(pInfo);
        jfregister.revalidate();
        jfregister.repaint();
        
    }//GEN-LAST:event_btnNextActionPerformed

    private void cbPermaAddressStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbPermaAddressStateChanged
        if(cbPermaAddress.isSelected()){
            txtPermaAddr_HouseNumber.setText("");
            txtPermaAddr_Street.setText("");
            txtPermaAddr_Barangay.setText("");
            txtPermaAddr_Province.setText("");
            txtPermaAddr_zipcode.setText("");
            txtPermaAddr_HouseNumber.setEnabled(false);
            txtPermaAddr_Street.setEnabled(false);
            txtPermaAddr_Barangay.setEnabled(false);
            txtPermaAddr_Province.setEnabled(false);
            txtPermaAddr_zipcode.setEnabled(false);
        }else{
            txtPermaAddr_HouseNumber.setEnabled(true);
            txtPermaAddr_Street.setEnabled(true);
            txtPermaAddr_Barangay.setEnabled(true);
            txtPermaAddr_Province.setEnabled(true);
            txtPermaAddr_zipcode.setEnabled(true);
        }
    }//GEN-LAST:event_cbPermaAddressStateChanged

    private void jrbtnGenderMaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbtnGenderMaleMouseClicked
        if(jrbtnGenderMale.isSelected())
            jrbtnGenderFemale.setSelected(false);
    }//GEN-LAST:event_jrbtnGenderMaleMouseClicked

    private void jrbtnGenderFemaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbtnGenderFemaleMouseClicked
        if(jrbtnGenderFemale.isSelected())
            jrbtnGenderMale.setSelected(false);
    }//GEN-LAST:event_jrbtnGenderFemaleMouseClicked

    private void jrbtnCVSingleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbtnCVSingleMouseClicked
        if(jrbtnCVSingle.isSelected()){
            jrbtnCVMarried.setSelected(false);
            jrbtnCVDivorced.setSelected(false);
        }
    }//GEN-LAST:event_jrbtnCVSingleMouseClicked

    private void jrbtnCVMarriedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbtnCVMarriedMouseClicked
        if(jrbtnCVMarried.isSelected()){
            jrbtnCVDivorced.setSelected(false);
            jrbtnCVSingle.setSelected(false);
        }
    }//GEN-LAST:event_jrbtnCVMarriedMouseClicked

    private void jrbtnCVDivorcedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbtnCVDivorcedMouseClicked
        if(jrbtnCVDivorced.isSelected()){
            jrbtnCVMarried.setSelected(false);
            jrbtnCVSingle.setSelected(false);
        }
    }//GEN-LAST:event_jrbtnCVDivorcedMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

        JFrame jfregister = (JFrame) SwingUtilities.getAncestorOfClass(JFrame.class, this);
        jplPersonInfo_form1 pInfoF1 = new jplPersonInfo_form1();
        jfregister.remove(this); 
        jfregister.getContentPane().add(pInfoF1);
        jfregister.revalidate();
        jfregister.repaint();
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        loadFormData();
    }//GEN-LAST:event_formAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbPermaAddress;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton jrbtnCVDivorced;
    private javax.swing.JRadioButton jrbtnCVMarried;
    private javax.swing.JRadioButton jrbtnCVSingle;
    private javax.swing.JRadioButton jrbtnGenderFemale;
    private javax.swing.JRadioButton jrbtnGenderMale;
    private javax.swing.JTextField txtPermaAddr_Barangay;
    private javax.swing.JTextField txtPermaAddr_HouseNumber;
    private javax.swing.JTextField txtPermaAddr_Province;
    private javax.swing.JTextField txtPermaAddr_Street;
    private javax.swing.JTextField txtPermaAddr_zipcode;
    private javax.swing.JTextField txtResAddr_Barangay;
    private javax.swing.JTextField txtResAddr_HouseNumber;
    private javax.swing.JTextField txtResAddr_Province;
    private javax.swing.JTextField txtResAddr_Street;
    private javax.swing.JTextField txtResAddr_zipcode;
    private javax.swing.JTextField txtnationality;
    private javax.swing.JTextField txtplaceOfBrith;
    // End of variables declaration//GEN-END:variables

    private void loadFormData() {
        String query = "SELECT \n" +
            "profile.nationality AS nationality, \n" +
            "profile.placeofbirth AS placeofbirth, \n" +
            "profile.gender AS gender, \n" +
            "profile.civilstatus AS civilstatus, \n" +
            "profile.res_Address_HouseNumber AS res_Address_HouseNumber, \n" +
            "profile.res_Address_Street AS res_Address_Street, \n" +
            "profile.res_Address_Barangay AS res_Address_Barangay, \n" +
            "profile.res_Address_Province AS res_Address_Province, \n" +
            "profile.res_Address_zipcode AS res_Address_zipcode, \n" +
            "profile.per_Address_HouseNumber AS per_Address_HouseNumber, \n" +
            "profile.per_Address_Street AS per_Address_Street, \n" +
            "profile.per_Address_Barangay AS per_Address_Barangay, \n" +
            "profile.per_Address_Province AS per_Address_Province, \n" +
            "profile.per_Address_zipcode AS per_Address_zipcode \n" +
            "FROM `tblaccount` AS acc\n" +
            "INNER JOIN `tblprofile` AS profile \n" +
            "ON acc.id = profile.profileID \n"+
            "WHERE acc.id = ?;";
            
        Connection con = null;
        try {
            
            con = DriverManager.getConnection(Database.dbURL, Database.dbUsername, Database.dbPassword);
            PreparedStatement checkStmt = con.prepareStatement(query);
            checkStmt.setInt(1, userID);
            ResultSet rs = checkStmt.executeQuery();
            
            while (rs.next()) {
                if(rs.getString("gender").equalsIgnoreCase("male"))
                    jrbtnGenderMale.setSelected(true);
                else if(rs.getString("gender").equalsIgnoreCase("female"))
                    jrbtnGenderFemale.setSelected(true);
                
                if(rs.getString("civilstatus").equalsIgnoreCase("single"))
                    jrbtnCVSingle.setSelected(true);
                else if(rs.getString("civilstatus").equalsIgnoreCase("married"))
                    jrbtnCVMarried.setSelected(true);
                else if(rs.getString("civilstatus").equalsIgnoreCase("divorced"))
                    jrbtnCVDivorced.setSelected(true);
                
                txtnationality.setText(rs.getString("nationality"));
                txtplaceOfBrith.setText(rs.getString("placeofbirth"));
                txtResAddr_HouseNumber.setText(rs.getString("res_Address_HouseNumber"));
                txtResAddr_Street.setText(rs.getString("res_Address_Street"));
                txtResAddr_Barangay.setText(rs.getString("res_Address_Barangay"));
                txtResAddr_Province.setText(rs.getString("res_Address_Province"));
                txtResAddr_zipcode.setText(rs.getString("res_Address_zipcode"));
                txtPermaAddr_HouseNumber.setText(rs.getString("per_Address_HouseNumber"));
                txtPermaAddr_Street.setText(rs.getString("per_Address_Street"));
                txtPermaAddr_Barangay.setText(rs.getString("per_Address_Barangay"));
                txtPermaAddr_Province.setText(rs.getString("per_Address_Province"));
                txtPermaAddr_zipcode.setText(rs.getString("per_Address_zipcode"));
                
            }
        
        } catch (SQLException ex) {
            System.out.println(ex);
        } finally {
            if (con != null) {
                try {
                    con.close();
                } catch (SQLException closeEx) {
                    System.out.println(closeEx);
                }
            }
        }
    }
}
