/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package io.fcash.dashboard.client;

import io.fcash.Database;
import io.fcash.dashboard.Login;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Champ
 */
public class accountHolder extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(accountHolder.class.getName());

    public static int userid;
    
    /**
     * Creates new form accountHolder
     */
    public accountHolder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnDeposit = new javax.swing.JButton();
        btnWithdraw = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAccount = new javax.swing.JTable();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Account List");

        btnSearch.setText("Search");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });

        btnDeposit.setText("Deposit");
        btnDeposit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDepositMouseClicked(evt);
            }
        });

        btnWithdraw.setText("Withdraw");
        btnWithdraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnWithdrawMouseClicked(evt);
            }
        });

        tblAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Account No.", "Full Name", "Available Balance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAccount);

        btnLogout.setText("LOG OUT");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(288, 288, 288)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(690, 564));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        refreshTableData();
    }//GEN-LAST:event_formWindowOpened

    private void btnDepositMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepositMouseClicked
        
        //get hidden ID
        int row = tblAccount.getSelectedRow();
        int modelRow = tblAccount.convertRowIndexToModel(row);
        int id = (int)tblAccount.getModel().getValueAt(modelRow, 0);
        
        double deposit_amount = -1;
        double current_balance = (double)tblAccount.getModel().getValueAt(modelRow, 2);
        
        boolean isValid = false;
        if(accountStatus(id).equals("Dormant")){
            JOptionPane.showMessageDialog(this, 
                    "Cannot Deposit. The account is Dormant State.", 
                    "Account", 
                    JOptionPane.INFORMATION_MESSAGE);
        }else if(accountStatus(id).equals("Frozen")){
            JOptionPane.showMessageDialog(this, 
                    "Cannot Deposit. The account is Frozen State.", 
                    "Account", 
                    JOptionPane.INFORMATION_MESSAGE);
        }else if(accountStatus(id).equals("Closed")){
            JOptionPane.showMessageDialog(this, 
                    "Cannot Deposit. The account is Closed.", 
                    "Account", 
                    JOptionPane.INFORMATION_MESSAGE);
        }else{
            while (!isValid) {
                String amount = JOptionPane.showInputDialog("Enter the amount to deposit:");

                try {
                    deposit_amount = Double.parseDouble(amount);

                    if(amount == null){
                        break;
                    } else if (deposit_amount > 0) {
                        int result = JOptionPane.showConfirmDialog(
                            null,
                            "Do you want to save changes?", 
                            "Confirm Action",
                            JOptionPane.YES_NO_OPTION
                        );
                        if (result == JOptionPane.YES_OPTION) {

                           String updateSavingsAccount = "UPDATE `tblsavingsaccount` SET `balance` = ? WHERE `tblsavingsaccount`.`id` = ?;";
                           String insertTransaction = "INSERT INTO `tbltransaction` (`costumerID`, `amount`, `transactionType`, `transactionDate`, `IssuedByID`) VALUES (?, ?, ?, current_timestamp(), ?)";

                           updateSavingsAccount(updateSavingsAccount, id, current_balance, deposit_amount, "deposit");
                           insertTransaction(insertTransaction, id, deposit_amount, "deposit", userid);
                           refreshTableData(); 

                           JOptionPane.showMessageDialog(null, "Transaction Complete.");
                           isValid = true;

                        }else{
                           isValid = false;
                        }
                    } else if(deposit_amount == 0){
                        break;
                    } else {
                        JOptionPane.showMessageDialog(null, "Error: Amount cannot be negative.");
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Error: Please enter a valid number.");
                }

            }
        }
        
        
    }//GEN-LAST:event_btnDepositMouseClicked

    private void btnWithdrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWithdrawMouseClicked

        //get hidden ID
        int row = tblAccount.getSelectedRow();
        int modelRow = 0;
        int id;
        
        double withdraw_amount = -1;
        double current_balance = (double)tblAccount.getModel().getValueAt(modelRow, 2);
        
        boolean isValid = false;
        
        if(row != -1){
            modelRow = tblAccount.convertRowIndexToModel(row);
            id = (int)tblAccount.getModel().getValueAt(modelRow, 0);
            while (!isValid) {
                String amount = JOptionPane.showInputDialog("Enter the amount to deposit:");

                try {
                    withdraw_amount = Double.parseDouble(amount);

                    if(amount == null){
                        break;
                    } else if (withdraw_amount > 0 && withdraw_amount<=current_balance) {
                        int result = JOptionPane.showConfirmDialog(
                            null,
                            "Do you want to save changes?", 
                            "Confirm Action",
                            JOptionPane.YES_NO_OPTION
                        );
                        if (result == JOptionPane.YES_OPTION) {
                           String updateSavingsAccount = "UPDATE `tblsavingsaccount` SET `balance` = ? WHERE `tblsavingsaccount`.`id` = ?;";
                           String insertTransaction = "INSERT INTO `tbltransaction` (`costumerID`, `amount`, `transactionType`, `transactionDate`, `IssuedByID`) VALUES (?, ?, ?, current_timestamp(), ?)";
                           
                           updateSavingsAccount(updateSavingsAccount, id, current_balance, withdraw_amount, "withdraw");
                           insertTransaction(insertTransaction, id, withdraw_amount, "withdraw", userid);
                           refreshTableData(); 
                           
                           JOptionPane.showMessageDialog(null, "Transaction Complete.");
                           isValid = true;
                           
                        }else{
                           isValid = false;
                        }
                    } else if(withdraw_amount == 0){
                        break;
                    } else {
                        JOptionPane.showMessageDialog(null, "Error: Amount cannot be negative.");
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Error: Please enter a valid number.");
                }

            }
        }
    }//GEN-LAST:event_btnWithdrawMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        DefaultTableModel tableModel = (DefaultTableModel) tblAccount.getModel();
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(tableModel);
        tblAccount.setRowSorter(sorter);
        if (txtSearch.getText().trim().equals("")) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + txtSearch.getText())); 
        }
    }//GEN-LAST:event_btnSearchMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new accountHolder().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAccount;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void refreshTableData() {
        String query = "SELECT \n" +
            "acc.id AS id, \n" +
            "profile.firstname AS firstname, \n" +
            "profile.middlename AS middlename, \n" +
            "profile.lastname AS lastname, \n" +
            "profile.suffix AS suffix, \n" +
            "accSave.balance AS balance\n" +
            "FROM `tblaccount` AS acc\n" +
            "INNER JOIN `tblprofile` AS profile \n" +
            "ON acc.id = profile.profileID\n" +
            "INNER JOIN `tblsavingsaccount` AS accSave \n" +
            "ON acc.id = accSave.id;";
        
        DefaultTableModel model = new DefaultTableModel(new String[]{"ID", "Full Name", "Balance"}, 0);
        Connection con = null;
        try {
            con = DriverManager.getConnection(Database.dbURL, Database.dbUsername, Database.dbPassword);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            
            
            while (rs.next()) {
                int id = rs.getInt("id");
                String fullname = rs.getString("lastname")+""+(rs.getString("suffix").trim().equals("")? "" : " "+rs.getString("suffix"))+", "+rs.getString("firstname")+" "+rs.getString("middlename");
                double balance = rs.getDouble("balance");

                // Add row to the model
                model.addRow(new Object[]{id, fullname, balance});
                
            }
            
            tblAccount.setModel(model);
            tblAccount.removeColumn(tblAccount.getColumnModel().getColumn(0));
        
        
        } catch (SQLException ex) {
            System.out.println(ex);
        } finally {
            if (con != null) {
                try {
                    con.close();
                } catch (SQLException closeEx) {
                    System.out.println(closeEx);
                }
            }
        }
        
    }

    private void updateSavingsAccount(String query, int id, double current_balance, double amount, String transactionType) {
        Connection con = null;
        try {
            con = DriverManager.getConnection(Database.dbURL, Database.dbUsername, Database.dbPassword);
            PreparedStatement pstmt = con.prepareStatement(query);
            if(transactionType.equalsIgnoreCase("deposit")){
                pstmt.setDouble(1, (current_balance+amount));
            }else if(transactionType.equalsIgnoreCase("withdraw")){
                pstmt.setDouble(1, (current_balance-amount));
            }
            pstmt.setInt(2, id);
            pstmt.executeUpdate();

        } catch (SQLException ex) {
            System.out.println(ex);
        } finally {
            if (con != null) {
                try {
                    con.close();
                } catch (SQLException closeEx) {
                    System.out.println(closeEx);
                }
            }
        }
    }

    private void insertTransaction(String query, int id, double amount, String transactionType, int clientID) {
        Connection con = null;
        try {
            con = DriverManager.getConnection(Database.dbURL, Database.dbUsername, Database.dbPassword);
            PreparedStatement pstmt = con.prepareStatement(query);
            pstmt.setDouble(1, id);
            pstmt.setDouble(2, amount);
            pstmt.setString(3, transactionType);
            pstmt.setInt(4, clientID);
            
            pstmt.executeUpdate();
            
        } catch (SQLException ex) {
            System.out.println(ex);
        } finally {
            if (con != null) {
                try {
                    con.close();
                } catch (SQLException closeEx) {
                    System.out.println(closeEx);
                }
            }
        }
    
    }

    private Object accountStatus(int id) {
        String status = "";
        String select_query = "SELECT acc.`id`, savAcc.`accountStatus` FROM `tblaccount` AS acc INNER JOIN `tblsavingsaccount` AS savAcc ON acc.id = savAcc.id WHERE acc.`id` = ?;";
            
        Connection con = null;
        ResultSet rs;
        try {
            con = DriverManager.getConnection(Database.dbURL, Database.dbUsername, Database.dbPassword);
            PreparedStatement pstmt = con.prepareStatement(select_query);
            pstmt.setInt(1, id);
            rs = pstmt.executeQuery();
            
            if(rs.next()){
                status = rs.getString("accountStatus");
                
            } 
            
        } catch (SQLException ex) {
            System.out.println(ex);
        } finally {
            if (con != null) {
                try {
                    con.close();
                } catch (SQLException closeEx) {
                    System.out.println(closeEx);
                }
            }
        }
        
        return status;
    }
}
